ALTER TABLE user
    ADD COLUMN account_id BIGINT NOT NULL;

ALTER TABLE user
    ADD CONSTRAINT FK_User_Account
    FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE ON UPDATE CASCADE