version: "3.8"
services:
#  axonserver:
#    image: axoniq/axonserver:latest
#    container_name: asxonserver
#    restart: always
#    ports:
#      - "8024:8024"
#      - "8124:8124"
#    networks:
#      - FanoosNet

  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      SERVICE_NAME: 'mysql'
      MYSQL_DATABASE: 'fanoosdb'
      MYSQL_USER: 'fanoosuser'
      MYSQL_PASSWORD: 'fanoospass'
      MYSQL_ROOT_PASSWORD: 'fanoosRootPsw'
    networks:
      - FanoosNet

  adminerdb:
    image: adminer:latest
    container_name: adminerdb
    depends_on:
      - mysqldb
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysqldb
    networks:
      - FanoosNet

#  mongodb:
#    image: mongo
#    container_name: mongodb
#    restart: always
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo-data:/data
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=rootuser
#      - MONGO_INITDB_ROOT_PASSWORD=rootpass
#    networks:
#      - FanoosNet

#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express
#    depends_on:
#      - mongodb
#    restart: always
#    ports:
#      - "8081:8081"
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
#      - ME_CONFIG_MONGODB_SERVER=mongodb
#    networks:
#      - FanoosNet

volumes:
  mongo-data: { }
  mysql-data: { }

networks:
  FanoosNet:
    driver: bridge